### ISSUE TITLE
Update event names/notes

### ISSUE THREAD

**Issue by tranzmatt** [ZoneMinder/pyzm#10]
I'd like to be able to use pyzm to update an event's name or notes.  Is that possible?  I can get an event name().  How can I set it?

**Comment by pliablepixels** [comment]
For now, you'll have to go low and use `_make_request` - See https://github.com/pliablepixels/zmeventnotification/blob/master/hook/zm_detect.py#L780-L831 - I added support in zm_detect.py to update notes with the detection string.
