### ISSUE TITLE
Documentation enhancement: AUTH_HASH_LOGINS must be enabled for file downloads

### ISSUE THREAD

**Issue by inactivist** [ZoneMinder/pyzm#11]
This may seem obvious to some, but you must enable AUTH_HASH_LOGINS option in order to use [`Event.download_image`](https://pyzm.readthedocs.io/en/latest/source/pyzm.html#pyzm.helpers.Event.Event.download_image) and [`Event.download_video`](https://pyzm.readthedocs.io/en/latest/source/pyzm.html#pyzm.helpers.Event.Event.download_video), at least on ZM version 1.32.3 version I'm using.  

ZM returns a login page, and `ZMapi._relogin()` has no effect, so the download attempt fails.

I haven't tested on newer ZM releases.  I will when I have time.

**Comment by pliablepixels** [comment]
done
