### ISSUE TITLE
Event Timestamp

### ISSUE THREAD

**Issue by pedromoraesh** [ZoneMinder/pyzm#12]
There is a way to get Event Start Time or End Time?

**Comment by pliablepixels** [comment]
Yes, if you just do `get()` on the event you'll get the full object and start/end will be part of it

**Comment by pedromoraesh** [comment]
Nice.

That API is awesome! Simple and work so easily.

I tried so many things to get Start and End from Events that almost give up from project!

Thanks!

**Comment by pliablepixels** [comment]
glad you liked it!
