### ISSUE TITLE
Add Event.delete() method

### ISSUE THREAD

**Issue by mludvig** [ZoneMinder/pyzm#18]
It would be very useful to have `Event.delete()` method. I wanted to use `pyzm` in my client for periodical cleanup of unwanted events (e.g. false positives or known motion) but am unable to remove them as there is no `delete()` event.

Thanks!

**Comment by mludvig** [comment]
Pull request #19  adds this support, it wasn't that hard :)

**Comment by mludvig** [comment]
PR merged, thanks. Closing.

**Comment by mludvig** [comment]
@pliablepixels any chance you could make a new release to pypi so I don't have to track git master with this functionality in my project? Please :)

**Comment by pliablepixels** [comment]
done
