### ISSUE TITLE
Event._download_file does not ignore SSL verification

### ISSUE THREAD

**Issue by themoosman** [ZoneMinder/pyzm#23]
When calling this from mlapi.py, and SSL verification is set to no (https://github.com/pliablepixels/mlapi/blob/master/mlapiconfig.ini#L49), this function does not inherit that setting.

So, in essence, when mlapi goes to download a file it will fail even if SSL verification is disabled.

https://github.com/pliablepixels/pyzm/blob/master/pyzm/helpers/Event.py#L217

The workaround is to set `REQUESTS_CA_BUNDLE` with the CA bundle.

**Comment by pliablepixels** [comment]
could you try master to see if it fixes?

**Comment by themoosman** [comment]
How can I easily test this?

**Comment by pliablepixels** [comment]
Assuming we can close this?

**Comment by themoosman** [comment]
Was it ever merged? I'm currently using a workaround.

**Comment by pliablepixels** [comment]
There is nothing to merge. Any code committed to master automatically gets incorporated to the next release.
